### ISSUE TITLE
Uploading more than 2 files, only uploads 2 files.

### ISSUE THREAD

**Issue by tfesslerCWC** [rahulrepal/react-firebase-filepond#1]
Selecting 3 files / or dropping 3 files / only uploads 2 files.  
It looks like the <filepond /> component should be making callbacks for all the files and it stops at 2.  Although, I could be wrong.

Below is the a of code from the bottom of fileshare.js

>         return(
>             <div className="fileshare">
>                         <FilePond
>                           ref={ref => (this.pond = ref)}
>                           files={this.state.files}
>                           allowMultiple={true}
>                           maxFiles={3}
>                           server = {{process :  this . handleProcessing . bind ( this  )}}
>                           oninit={() => this.handleInit()}
>                         >
>                           { this.state.files.map(file=> (
>                                 <File key = {file} source = {file} />
>                               ))}
>                         </FilePond>
>             </div>
>         )

Following up.    Comparing to react-firebase-cloud-storage,  the only major difference I could see was the library versions.   

More info...   Dropping to earlier versions in package.json fixes the problem.

> Original:
>   "dependencies": {
>     "filepond": "^4.3.5",
>     "filepond-plugin-image-preview": "^4.0.5",
>     "firebase": "^5.9.2",
>     "react": "^16.8.6",
>     "react-dom": "^16.8.6",
>     "react-filepond": "^7.0.1",
>     "react-scripts": "2.1.8"

> Working...
>  "dependencies": {
>     "filepond-plugin-image-preview": "^1.0.8",
>     "firebase": "^6.1.0", 
>     "react": "^16.8.6", 
>     "react-dom": "^16.8.6",  
>     "react-filepond": "^2.0.2", 
>     "react-scripts": "3.0.0"

**Comment by rahulrepal** [comment]
Yeah more or less it is same as react-firebase-cloud-storage as from the documentation of filepond things were unclear and the template they provide is unnecessary so rather changing things manually which would need more time to research into filepond library I made the code similar to react-firebase-cloud-storage because I had to rush this application for my college project.
